# Generated by Django 4.0.2 on 2022-09-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_alter_producto_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('localidad', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=50)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=10)),
                ('secuencia', models.IntegerField()),
                ('messec', models.CharField(max_length=2)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('num_orden', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='inventario.almacen', verbose_name='Destino')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origen', to='inventario.almacen', verbose_name='Origen')),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LOC_Destino', to='inventario.localidades', verbose_name='LOC Destino')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LOC_Origen', to='inventario.localidades', verbose_name='LOC_Origen')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto', verbose_name='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reglas_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('retraso', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('metodo_abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.metodo_abastecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('controllote', models.BooleanField(default=False)),
                ('statuslote', models.BooleanField(default=True)),
                ('existencia', models.IntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.localidades', verbose_name='LOC')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.producto')),
            ],
        ),
        migrations.AddField(
            model_name='almacen',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.metodo_abastecimiento', verbose_name='abastecimiento'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='reglas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.reglas_inventario'),
        ),
    ]
