# Generated by Django 4.0.2 on 2022-05-04 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('secuencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('credito_apertura', models.FloatField()),
                ('debito_apertura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista_de_precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad1', models.IntegerField()),
                ('cantidad2', models.IntegerField()),
                ('cantidad3', models.IntegerField()),
                ('cantidad4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('divisa', models.CharField(max_length=2)),
                ('moneda', models.CharField(max_length=30)),
                ('simbolo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('multiplicador', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tasa', models.FloatField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=50)),
                ('secuencia', models.IntegerField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Reglas_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('retraso', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('metodo_abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.metodo_abastecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('barcode', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('metodo_costo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('entrada', models.IntegerField()),
                ('precio', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoria_productos')),
                ('cuenta_de_entrada_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_entrada', to='product.cuenta')),
                ('cuenta_de_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_gasto', to='product.cuenta')),
                ('cuenta_de_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_ingreso', to='product.cuenta')),
                ('cuenta_de_salida_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_salida', to='product.cuenta')),
                ('item_lista_de_precios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.lista_de_precios')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_transacciones', to='product.moneda')),
                ('moneda_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_costo', to='product.moneda')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='lista_de_precios',
            name='tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.tarifa'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.moneda'),
        ),
    ]
