# Generated by Django 4.0.2 on 2022-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
