# Generated by Django 4.0.2 on 2022-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(default='puerto plata', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.CharField(default='info@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(default='Suplidora Juan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='rnc',
            field=models.CharField(default='101-00234202', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(default='809-586-8974', max_length=15),
            preserve_default=False,
        ),
    ]
