# Generated by Django 4.0.2 on 2022-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_proveedortipo_proveedores_contacto_proveedores_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank='True', to='product.Proveedores'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='productos',
            field=models.ManyToManyField(through='product.Producto', to='product.Proveedores'),
        ),
    ]
