# Generated by Django 4.0.2 on 2022-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producto_proveedores_proveedores_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='product.Proveedores'),
        ),
    ]
